adminUser: admin
adminPassword: admin

service:
  type: NodePort
  nodePort: 32000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: true

persistence:
  enabled: true
  storageClassName: ""  # leave empty to use the default storage class
  accessModes:
    - ReadWriteOnce
  size: 1Gi
