# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY . /app

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y tini
RUN apt-get update && \
    apt-get install -y --no-install-recommends procps && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y procps net-tools netcat-traditional
RUN adduser --disabled-password --gecos "" appuser && chown -R appuser /app
# Переключаемся на нового пользователя
USER appuser


ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["python", "dev_tg.py"]

# docker build -f dockerfile_tg -t dev_tg .
# docker run --rm -it --network host -v /home/nik/git/my_tg_chan/jpgs:/app/jpgs \--name my_dev_tg --env-file ../.env dev_tg
#