apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jpgs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Add your environment variables here
  # Example:
  # TELEGRAM_BOT_TOKEN: "your-bot-token"
  # REDIS_HOST: "redis"
  # REDIS_PORT: "6379" 